# Generated by Django 5.1.4 on 2024-12-25 15:37

import django.db.models.deletion
import rizzder_app.entity.user
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('chat_message_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('date', models.BigIntegerField(default=0)),
                ('value', models.CharField(default='', max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('user_image_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('image', models.CharField(default='', max_length=1000)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=1000)),
                ('description_encoded_64', models.CharField(default='', max_length=100000)),
                ('birth_date', models.DateField(default='1970-01-01')),
                ('gender', models.IntegerField(default=rizzder_app.entity.user.Gender['MAN'], verbose_name=rizzder_app.entity.user.Gender)),
                ('gender_preference', models.IntegerField(default=rizzder_app.entity.user.Gender['MAN'], verbose_name=rizzder_app.entity.user.Gender)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('score', models.FloatField(default=1000)),
                ('blocked_users', models.ManyToManyField(blank=True, to='rizzder_app.user')),
                ('credential', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('images', models.ManyToManyField(to='rizzder_app.userimage')),
            ],
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('chat_room_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=10000)),
                ('messages', models.ManyToManyField(to='rizzder_app.chatmessage')),
                ('users', models.ManyToManyField(to='rizzder_app.user')),
            ],
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='user_sender',
            field=models.ManyToManyField(to='rizzder_app.user'),
        ),
        migrations.CreateModel(
            name='UserLike',
            fields=[
                ('user_like_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('like', models.BooleanField(default=False)),
                ('date', models.DateField(default='1970-01-01')),
                ('user_liker', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_liker', to='rizzder_app.user')),
                ('user_receiver', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_receiver', to='rizzder_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserMatch',
            fields=[
                ('user_match_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('date', models.BigIntegerField(default=0)),
                ('user_first', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_first', to='rizzder_app.user')),
                ('user_second', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_second', to='rizzder_app.user')),
            ],
        ),
    ]
