# Generated by Django 5.1.4 on 2025-01-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rizzder_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_online',
            field=models.BigIntegerField(default=0),
        ),
    ]
