# Generated by Django 5.1.4 on 2025-01-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rizzder_app', '0002_user_last_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
